"""initial_auth_schema

Revision ID: eca82c108eac
Revises: 
Create Date: 2026-03-26 15:18:20.924171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca82c108eac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('verification_link', sa.String(length=500), nullable=True),
    sa.Column('attachment_file_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_file_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certification_entry_user_id'), 'certification_entry', ['user_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_company_user_name')
    )
    op.create_index(op.f('ix_company_user_id'), 'company', ['user_id'], unique=False)
    op.create_table('course_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('completed_on', sa.Date(), nullable=True),
    sa.Column('duration_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('verification_link', sa.String(length=500), nullable=True),
    sa.Column('attachment_file_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_file_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_mime_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_entry_user_id'), 'course_entry', ['user_id'], unique=False)
    op.create_table('education_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_entry_user_id'), 'education_entry', ['user_id'], unique=False)
    op.create_table('experience_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('seniority', sa.String(length=100), nullable=True),
    sa.Column('compensation_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), nullable=True),
    sa.Column('compensation_period', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_entry_user_id'), 'experience_entry', ['user_id'], unique=False)
    op.create_table('job_platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('applications_url', sa.String(length=500), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('manual_resume', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_platform_user_id'), 'job_platform', ['user_id'], unique=False)
    op.create_table('platform_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('applications_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_about_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_about_me_user_id'), 'profile_about_me', ['user_id'], unique=False)
    op.create_table('profile_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_data_user_id'), 'profile_data', ['user_id'], unique=False)
    op.create_table('project_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_entry_user_id'), 'project_entry', ['user_id'], unique=False)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_resume_user_name')
    )
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=False)
    op.create_table('skill_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_group_user_id'), 'skill_group', ['user_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('pay_period', sa.String(length=20), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['platform_id'], ['job_platform.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('education_highlight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('education_entry_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['education_entry_id'], ['education_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_highlight_education_entry_id'), 'education_highlight', ['education_entry_id'], unique=False)
    op.create_index(op.f('ix_education_highlight_user_id'), 'education_highlight', ['user_id'], unique=False)
    op.create_table('experience_bullet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('experience_entry_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experience_entry_id'], ['experience_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_bullet_experience_entry_id'), 'experience_bullet', ['experience_entry_id'], unique=False)
    op.create_index(op.f('ix_experience_bullet_user_id'), 'experience_bullet', ['user_id'], unique=False)
    op.create_table('project_bullet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('project_entry_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_entry_id'], ['project_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_bullet_project_entry_id'), 'project_bullet', ['project_entry_id'], unique=False)
    op.create_index(op.f('ix_project_bullet_user_id'), 'project_bullet', ['user_id'], unique=False)
    op.create_table('skill_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('skill_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_group_id'], ['skill_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_item_skill_group_id'), 'skill_item', ['skill_group_id'], unique=False)
    op.create_index(op.f('ix_skill_item_user_id'), 'skill_item', ['user_id'], unique=False)
    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_history_user_id'), 'application_history', ['user_id'], unique=False)
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_user_id'), 'appointment', ['user_id'], unique=False)
    op.execute("CREATE UNIQUE INDEX uq_company_name_ci_per_user ON company (user_id, LOWER(name));")
    op.execute(
        """
        INSERT INTO platform_template (name, icon, base_url, applications_url)
        VALUES
          ('LinkedIn', 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/linkedin.svg', 'https://www.linkedin.com', 'https://www.linkedin.com/my-items/saved-jobs/'),
          ('Gupy', NULL, 'https://portal.gupy.io', 'https://portal.gupy.io/job-search/term'),
          ('Indeed', 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/indeed.svg', 'https://www.indeed.com', 'https://my.indeed.com/resume'),
          ('Glassdoor', 'https://cdn.jsdelivr.net/npm/simple-icons@v11/icons/glassdoor.svg', 'https://www.glassdoor.com', 'https://www.glassdoor.com/member/profile/index.htm'),
          ('Catho', NULL, 'https://www.catho.com.br', 'https://www.catho.com.br/candidaturas/')
        ON CONFLICT DO NOTHING
        """
    )
    user_owned_tables = [
        "resume",
        "profile_data",
        "job_platform",
        "company",
        "application",
        "application_history",
        "appointment",
        "experience_entry",
        "experience_bullet",
        "education_entry",
        "education_highlight",
        "project_entry",
        "project_bullet",
        "skill_group",
        "skill_item",
        "certification_entry",
        "course_entry",
        "profile_about_me",
    ]
    for table_name in user_owned_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY;")
        op.execute(
            f"""
            CREATE POLICY {table_name}_select_own ON {table_name}
            FOR SELECT TO authenticated
            USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);
            """
        )
        op.execute(
            f"""
            CREATE POLICY {table_name}_insert_own ON {table_name}
            FOR INSERT TO authenticated
            WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);
            """
        )
        op.execute(
            f"""
            CREATE POLICY {table_name}_update_own ON {table_name}
            FOR UPDATE TO authenticated
            USING (auth.uid() IS NOT NULL AND auth.uid() = user_id)
            WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);
            """
        )
        op.execute(
            f"""
            CREATE POLICY {table_name}_delete_own ON {table_name}
            FOR DELETE TO authenticated
            USING (auth.uid() IS NOT NULL AND auth.uid() = user_id);
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_owned_tables = [
        "resume",
        "profile_data",
        "job_platform",
        "company",
        "application",
        "application_history",
        "appointment",
        "experience_entry",
        "experience_bullet",
        "education_entry",
        "education_highlight",
        "project_entry",
        "project_bullet",
        "skill_group",
        "skill_item",
        "certification_entry",
        "course_entry",
        "profile_about_me",
    ]
    for table_name in user_owned_tables:
        op.execute(f"DROP POLICY IF EXISTS {table_name}_select_own ON {table_name};")
        op.execute(f"DROP POLICY IF EXISTS {table_name}_insert_own ON {table_name};")
        op.execute(f"DROP POLICY IF EXISTS {table_name}_update_own ON {table_name};")
        op.execute(f"DROP POLICY IF EXISTS {table_name}_delete_own ON {table_name};")
        op.execute(f"ALTER TABLE {table_name} NO FORCE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table_name} DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP INDEX IF EXISTS uq_company_name_ci_per_user;")
    op.drop_index(op.f('ix_appointment_user_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_application_history_user_id'), table_name='application_history')
    op.drop_table('application_history')
    op.drop_index(op.f('ix_skill_item_user_id'), table_name='skill_item')
    op.drop_index(op.f('ix_skill_item_skill_group_id'), table_name='skill_item')
    op.drop_table('skill_item')
    op.drop_index(op.f('ix_project_bullet_user_id'), table_name='project_bullet')
    op.drop_index(op.f('ix_project_bullet_project_entry_id'), table_name='project_bullet')
    op.drop_table('project_bullet')
    op.drop_index(op.f('ix_experience_bullet_user_id'), table_name='experience_bullet')
    op.drop_index(op.f('ix_experience_bullet_experience_entry_id'), table_name='experience_bullet')
    op.drop_table('experience_bullet')
    op.drop_index(op.f('ix_education_highlight_user_id'), table_name='education_highlight')
    op.drop_index(op.f('ix_education_highlight_education_entry_id'), table_name='education_highlight')
    op.drop_table('education_highlight')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_skill_group_user_id'), table_name='skill_group')
    op.drop_table('skill_group')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_project_entry_user_id'), table_name='project_entry')
    op.drop_table('project_entry')
    op.drop_index(op.f('ix_profile_data_user_id'), table_name='profile_data')
    op.drop_table('profile_data')
    op.drop_index(op.f('ix_profile_about_me_user_id'), table_name='profile_about_me')
    op.drop_table('profile_about_me')
    op.drop_table('platform_template')
    op.drop_index(op.f('ix_job_platform_user_id'), table_name='job_platform')
    op.drop_table('job_platform')
    op.drop_index(op.f('ix_experience_entry_user_id'), table_name='experience_entry')
    op.drop_table('experience_entry')
    op.drop_index(op.f('ix_education_entry_user_id'), table_name='education_entry')
    op.drop_table('education_entry')
    op.drop_index(op.f('ix_course_entry_user_id'), table_name='course_entry')
    op.drop_table('course_entry')
    op.drop_index(op.f('ix_company_user_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_certification_entry_user_id'), table_name='certification_entry')
    op.drop_table('certification_entry')
    # ### end Alembic commands ###
